name: Nightly

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:preview
        