name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  gh-release:
    name: Upload Release Asset
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies & build
        run: |
          yarn install
          yarn build
      - name: Package artifact
        working-directory: "dist"
        run: zip -r ../homergx.zip ./*
      - name: Publish release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: homergx.zip

  docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        